# @author: Memba Co.

# === UYGULAMA VERSİYONU ===
APP_VERSION = "1.8.0" # Mimari iyileştirme ve Telegram'dan pozisyon kapatma eklendi

# === YAPAY ZEKA MODEL AYARI ===
GEMINI_MODEL = 'gemini-1.5-flash' # veya kullandığınız diğer model

# === STRATEJİ AYARLARI ===
USE_MTA_ANALYSIS = True
MTA_TREND_TIMEFRAME = "4h"

# HABER ANALİZİ AYARI
# Botun işlem kararı verirken CryptoPanic API'si üzerinden haberleri kontrol edip etmeyeceğini belirler.
USE_NEWS_ANALYSIS = False

# === CANLI İŞLEM AYARI (DİKKAT!) ===
LIVE_TRADING = False

# === EMİR TÜRÜ VE STRATEJİSİ AYARLARI ===
DEFAULT_ORDER_TYPE = 'LIMIT'
USE_AI_LIMIT_PRICE = True

# === TEMEL AYARLAR ===
DEFAULT_MARKET_TYPE = 'future'

# === KALDIRAÇ AYARLARI ===
LEVERAGE = 10.0

# === RİSK YÖNETİMİ AYARLARI ===
RISK_PER_TRADE_PERCENT = 5.0

# --- Stop-Loss Ayarları ---
USE_ATR_FOR_SLTP = True 
ATR_MULTIPLIER_SL = 2.0 

# === KÂR ALMA STRATEJİLERİ ===
# --- Ana Kâr Al (Take-Profit) Hedefi ---
RISK_REWARD_RATIO_TP = 2.0 

# --- İz Süren Zarar Durdur (Trailing Stop-Loss) ---
USE_TRAILING_STOP_LOSS = True
TRAILING_STOP_ACTIVATION_PERCENT = 1.5

# --- Kısmi Kâr Alma (Partial Take-Profit) ---
USE_PARTIAL_TP = True 
PARTIAL_TP_TARGET_RR = 1.0 
PARTIAL_TP_CLOSE_PERCENT = 50.0 

# === POZİSYON YÖNETİMİ AYARLARI ===
MAX_CONCURRENT_TRADES = 5
DATABASE_FILE = "data/trades.db"
POSITION_CHECK_INTERVAL_SECONDS = 60

# === TELEGRAM BİLDİRİM AYARLARI ===
TELEGRAM_ENABLED = True

# === PROAKTİF TARAMA AYARLARI ===
PROACTIVE_SCAN_ENABLED = True
PROACTIVE_SCAN_INTERVAL_SECONDS = 900
PROACTIVE_SCAN_AUTO_CONFIRM = False
PROACTIVE_SCAN_IN_LOOP = False
PROACTIVE_SCAN_USE_GAINERS_LOSERS = True
PROACTIVE_SCAN_TOP_N = 10
PROACTIVE_SCAN_MIN_VOLUME_USDT = 1000000
PROACTIVE_SCAN_BLACKLIST = ["SHIB", "PEPE", "MEME"]
PROACTIVE_SCAN_WHITELIST = ["BTC", "ETH", "SOL"]
PROACTIVE_SCAN_MTA_ENABLED = True
PROACTIVE_SCAN_ENTRY_TIMEFRAME = "1h"
PROACTIVE_SCAN_TREND_TIMEFRAME = "4h"
