# docker-compose.yml
# @author: Memba Co.

# Docker Compose sürüm 3.8'i kullanıyoruz.
version: '3.8'

# Çalıştırılacak servisleri tanımlıyoruz.
services:
  # Uygulamamızın ana servisi
  gemini-agent:
    # İmajı, projenin ana dizinindeki Dockerfile'dan oluştur.
    build: .
    # Konteyner bir hata nedeniyle durursa, manuel olarak durdurulmadıkça yeniden başlat.
    restart: unless-stopped
    
    # DÜZELTME: 'env_file' direktifi tamamen kaldırıldı.
    # Umbrel, umbrel-app.yml dosyasındaki 'env' listesine göre
    # gerekli ortam değişkenlerini kurulum sırasında kullanıcıya sorarak
    # konteynere kendisi enjekte edecektir. Bu, daha güvenli ve uyumlu bir yöntemdir.

    # Veritabanı dosyalarını içeren 'data' klasörünü kalıcı hale getirir.
    volumes:
      - ./data:/app/data
      
    # Konteynerin 8000 portunu, dışarıdan erişim için makinenin 8080 portuna bağla.
    ports:
      - "8080:8000"
      
    # Servislerin birbirleriyle iletişim kuracağı ağı tanımla.
    networks:
      - gemini-agent-net

# Uygulama için özel bir ağ oluşturuyoruz.
networks:
  gemini-agent-net:
    driver: bridge
